# -*- coding: utf-8 -*-
"""ML_Preprocessing_Feature_Selection_Titanicipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tXQbcXydEfV1VQ-JYtHAkSijHW_Nl_-r
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print("Libraries imported successfully!")

# Load Titanic dataset

url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv"

df = pd.read_csv(url)

print("Dataset loaded successfully!")
print("Shape of dataset:", df.shape)

# First 5 records
print("FIRST 5 RECORDS:")
display(df.head())

# Last 5 records
print("\nLAST 5 RECORDS:")
display(df.tail())

# Shape
print("\nDATASET SHAPE:")
print(df.shape)

# Column names
print("COLUMN NAMES:")
print(df.columns.tolist())

# Data types
print("\nDATA TYPES:")
print(df.dtypes)

# Number of unique values
print("\nUNIQUE VALUES:")
print(df.nunique())

# Missing values
print("\nMISSING VALUES:")
print(df.isnull().sum())

# Basic descriptive statistics

print("BASIC STATISTICS:")
display(df.describe())

# Mean
print("\nMEAN:")
print(df.mean(numeric_only=True))

# Median
print("\nMEDIAN:")
print(df.median(numeric_only=True))

# Mode
print("\nMODE:")
display(df.mode(numeric_only=True))

# Variance
print("\nVARIANCE:")
print(df.var(numeric_only=True))

# Standard Deviation
print("\nSTANDARD DEVIATION:")
print(df.std(numeric_only=True))

# Range for numerical columns only
numeric_df = df.select_dtypes(include=np.number)

print("\nRANGE:")
print(numeric_df.max() - numeric_df.min())

# Mean calculation from scratch

def mean_from_scratch(values):
    values = [x for x in values if pd.notna(x)]
    total = 0

    for x in values:
        total += x

    return total / len(values)


age_values = df["age"].tolist()

manual_mean = mean_from_scratch(age_values)

print("Mean of Age (from scratch):", manual_mean)
print("Pandas Mean:", df["age"].mean())

# Select Age values and remove missing values
age = df["age"].dropna().tolist()

# ---------------- MEDIAN ----------------
def median_from_scratch(values):
    values = sorted(values)
    n = len(values)

    if n % 2 == 1:
        return values[n // 2]
    else:
        return (values[n // 2 - 1] + values[n // 2]) / 2


# ---------------- MODE ----------------
def mode_from_scratch(values):
    frequency = {}

    for x in values:
        frequency[x] = frequency.get(x, 0) + 1

    max_frequency = max(frequency.values())

    modes = [x for x, count in frequency.items()
             if count == max_frequency]

    return modes


# ---------------- VARIANCE ----------------
def variance_from_scratch(values):
    mean = sum(values) / len(values)

    squared_diff = 0
    for x in values:
        squared_diff += (x - mean) ** 2

    return squared_diff / (len(values) - 1)


# ---------------- STANDARD DEVIATION ----------------
def std_from_scratch(values):
    return variance_from_scratch(values) ** 0.5


# ---------------- RANGE ----------------
def range_from_scratch(values):
    return max(values) - min(values)


# Results
print("Median:", median_from_scratch(age))
print("Pandas Median:", df["age"].median())

print("\nMode:", mode_from_scratch(age))
print("Pandas Mode:", df["age"].mode().tolist())

print("\nVariance:", variance_from_scratch(age))
print("Pandas Variance:", df["age"].var())

print("\nStandard Deviation:", std_from_scratch(age))
print("Pandas Standard Deviation:", df["age"].std())

print("\nRange:", range_from_scratch(age))
print("Pandas Range:", df["age"].max() - df["age"].min())

# Missing value analysis

missing_count = df.isnull().sum()

missing_percentage = (missing_count / len(df)) * 100

missing_table = pd.DataFrame({
    "Missing Values": missing_count,
    "Missing Percentage": missing_percentage.round(2)
})

print("MISSING VALUE ANALYSIS:")
display(missing_table)

# Create a copy for cleaning
df_clean = df.copy()

# -------- AGE: Median Imputation --------
age_median = df_clean["age"].median()

for i in range(len(df_clean)):
    if pd.isna(df_clean.loc[i, "age"]):
        df_clean.loc[i, "age"] = age_median


# -------- EMBARKED: Mode Imputation --------
embarked_mode = df_clean["embarked"].mode()[0]

for i in range(len(df_clean)):
    if pd.isna(df_clean.loc[i, "embarked"]):
        df_clean.loc[i, "embarked"] = embarked_mode


# -------- EMBARK_TOWN: Mode Imputation --------
embark_town_mode = df_clean["embark_town"].mode()[0]

for i in range(len(df_clean)):
    if pd.isna(df_clean.loc[i, "embark_town"]):
        df_clean.loc[i, "embark_town"] = embark_town_mode


# -------- DECK: Remove high-missing column --------
df_clean = df_clean.drop(columns=["deck"])


print("Missing value treatment completed!")
print("\nMissing values AFTER treatment:")
print(df_clean.isnull().sum())

# Check duplicate records

duplicate_count = df_clean.duplicated().sum()

print("Number of duplicate rows:", duplicate_count)

if duplicate_count == 0:
    print("No duplicate records found.")
else:
    print("Duplicate records found.")

# Remove duplicate records

before_duplicates = len(df_clean)

df_clean = df_clean.drop_duplicates().reset_index(drop=True)

after_duplicates = len(df_clean)

print("Rows before removing duplicates:", before_duplicates)
print("Duplicate rows removed:", before_duplicates - after_duplicates)
print("Rows after removing duplicates:", after_duplicates)

print("\nDuplicate rows remaining:", df_clean.duplicated().sum())

# Check for invalid numerical values

print("AGE CHECK")
print("Minimum Age:", df_clean["age"].min())
print("Maximum Age:", df_clean["age"].max())

print("\nFARE CHECK")
print("Minimum Fare:", df_clean["fare"].min())
print("Maximum Fare:", df_clean["fare"].max())


# Check categorical values
print("\nSEX CATEGORIES:")
print(df_clean["sex"].unique())

print("\nEMBARKED CATEGORIES:")
print(df_clean["embarked"].unique())

print("\nCLASS CATEGORIES:")
print(df_clean["class"].unique())

# Label Encoding from scratch

df_encoded = df_clean.copy()

# Create encoded column
df_encoded["sex_encoded"] = 0

for i in range(len(df_encoded)):
    if df_encoded.loc[i, "sex"] == "male":
        df_encoded.loc[i, "sex_encoded"] = 1
    else:
        df_encoded.loc[i, "sex_encoded"] = 0

print("Label Encoding completed!")

display(
    df_encoded[["sex", "sex_encoded"]].head(10)
)

# One-Hot Encoding from scratch

categories = sorted(df_encoded["embarked"].unique())

for category in categories:
    new_column = "embarked_" + str(category)
    df_encoded[new_column] = 0

    for i in range(len(df_encoded)):
        if df_encoded.loc[i, "embarked"] == category:
            df_encoded.loc[i, new_column] = 1

# Remove original categorical column
df_encoded = df_encoded.drop(columns=["embarked"])

print("One-Hot Encoding completed!")

display(
    df_encoded[
        ["embarked_C", "embarked_Q", "embarked_S"]
    ].head(10)
)

# IQR Outlier Detection from scratch

fare = df_encoded["fare"].dropna().tolist()

# Sort values
fare_sorted = sorted(fare)

# Function to calculate percentile
def percentile_from_scratch(values, p):
    n = len(values)
    position = (n - 1) * p

    lower = int(position)
    upper = lower + 1

    if upper >= n:
        return values[lower]

    weight = position - lower

    return values[lower] + weight * (values[upper] - values[lower])


# Calculate Q1 and Q3
Q1 = percentile_from_scratch(fare_sorted, 0.25)
Q3 = percentile_from_scratch(fare_sorted, 0.75)

# IQR
IQR = Q3 - Q1

# Lower and upper limits
lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

# Find outliers
outliers = []

for value in fare:
    if value < lower_limit or value > upper_limit:
        outliers.append(value)

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower Limit:", lower_limit)
print("Upper Limit:", upper_limit)
print("Number of IQR Outliers:", len(outliers))

# Z-Score Outlier Detection from scratch

fare = df_encoded["fare"].dropna().tolist()

# Calculate mean
mean_fare = sum(fare) / len(fare)

# Calculate standard deviation
squared_diff = 0

for x in fare:
    squared_diff += (x - mean_fare) ** 2

std_fare = (squared_diff / (len(fare) - 1)) ** 0.5

# Calculate Z-scores
z_scores = []

for x in fare:
    z = (x - mean_fare) / std_fare
    z_scores.append(z)

# Detect outliers
z_outliers = []

for i in range(len(fare)):
    if abs(z_scores[i]) > 3:
        z_outliers.append(fare[i])

print("Mean Fare:", mean_fare)
print("Standard Deviation:", std_fare)
print("Number of Z-score Outliers:", len(z_outliers))

# Outlier Treatment using IQR Capping

df_outlier_treated = df_encoded.copy()

for i in range(len(df_outlier_treated)):
    value = df_outlier_treated.loc[i, "fare"]

    if value < lower_limit:
        df_outlier_treated.loc[i, "fare"] = lower_limit

    elif value > upper_limit:
        df_outlier_treated.loc[i, "fare"] = upper_limit

print("Outlier treatment completed!")

print("\nOriginal Fare Statistics:")
print(df_encoded["fare"].describe())

print("\nAfter Outlier Treatment:")
print(df_outlier_treated["fare"].describe())

# Log Transformation

df_transformed = df_outlier_treated.copy()

# Apply log transformation to Fare
df_transformed["fare_log"] = np.log1p(df_transformed["fare"])

print("Log transformation completed!")

display(
    df_transformed[["fare", "fare_log"]].head(10)
)

# Min-Max Normalization from scratch

df_scaled = df_transformed.copy()

fare_values = df_scaled["fare_log"].tolist()

min_fare = min(fare_values)
max_fare = max(fare_values)

normalized_values = []

for x in fare_values:
    normalized = (x - min_fare) / (max_fare - min_fare)
    normalized_values.append(normalized)

df_scaled["fare_minmax"] = normalized_values

print("Min-Max Normalization completed!")

print("Minimum after scaling:", df_scaled["fare_minmax"].min())
print("Maximum after scaling:", df_scaled["fare_minmax"].max())

display(
    df_scaled[["fare_log", "fare_minmax"]].head(10)
)

# Standardization from scratch

values = df_scaled["fare_log"].tolist()

# Calculate mean
mean_value = sum(values) / len(values)

# Calculate standard deviation
squared_diff = 0

for x in values:
    squared_diff += (x - mean_value) ** 2

std_value = (squared_diff / (len(values) - 1)) ** 0.5

# Standardize each value
standardized_values = []

for x in values:
    z = (x - mean_value) / std_value
    standardized_values.append(z)

df_scaled["fare_standardized"] = standardized_values

print("Standardization completed!")

print("Mean after standardization:",
      df_scaled["fare_standardized"].mean())

print("Standard deviation after standardization:",
      df_scaled["fare_standardized"].std())

display(
    df_scaled[["fare_log", "fare_standardized"]].head(10)
)

# Before vs After Scaling Visualization

plt.figure(figsize=(12, 5))

plt.subplot(1, 2, 1)
plt.hist(df_outlier_treated["fare"], bins=30)
plt.title("Fare Before Transformation")
plt.xlabel("Fare")
plt.ylabel("Frequency")

plt.subplot(1, 2, 2)
plt.hist(df_transformed["fare_log"], bins=30)
plt.title("Fare After Log Transformation")
plt.xlabel("Log(Fare + 1)")
plt.ylabel("Frequency")

plt.tight_layout()
plt.show()

# Train-Test Split from scratch

np.random.seed(42)

# Create row indices
indices = np.arange(len(df_scaled))

# Shuffle indices
np.random.shuffle(indices)

# 80% training, 20% testing
split_point = int(0.80 * len(indices))

train_indices = indices[:split_point]
test_indices = indices[split_point:]

# Create train and test datasets
train_data = df_scaled.iloc[train_indices].copy()
test_data = df_scaled.iloc[test_indices].copy()

print("Train-Test Split Completed!")

print("\nTotal rows:", len(df_scaled))
print("Training rows:", len(train_data))
print("Testing rows:", len(test_data))

print("\nTraining percentage:",
      round(len(train_data) / len(df_scaled) * 100, 2), "%")

print("Testing percentage:",
      round(len(test_data) / len(df_scaled) * 100, 2), "%")

# Data Leakage Prevention Demonstration

print("TRAINING DATA:")
print("Training rows:", len(train_data))

print("\nTEST DATA:")
print("Testing rows:", len(test_data))

print("\nData Leakage Rule:")
print("Preprocessing parameters must be learned from TRAINING data only.")
print("The same parameters are then applied to TEST data.")

# Variance Threshold Feature Selection from scratch

# Select numerical columns
numeric_features = train_data.select_dtypes(include=np.number).columns.tolist()

# Remove target variable
if "survived" in numeric_features:
    numeric_features.remove("survived")

variance_results = {}

for feature in numeric_features:
    values = train_data[feature].dropna().tolist()

    mean_value = sum(values) / len(values)

    squared_diff = 0
    for x in values:
        squared_diff += (x - mean_value) ** 2

    variance = squared_diff / (len(values) - 1)

    variance_results[feature] = variance


variance_table = pd.DataFrame(
    list(variance_results.items()),
    columns=["Feature", "Variance"]
)

print("Variance of numerical features:")
display(variance_table.sort_values("Variance"))

# Pearson Correlation from scratch

target = train_data["survived"].tolist()

pearson_results = {}

for feature in numeric_features:

    x = train_data[feature].tolist()
    y = target

    # Mean of X and Y
    mean_x = sum(x) / len(x)
    mean_y = sum(y) / len(y)

    numerator = 0
    sum_x_squared = 0
    sum_y_squared = 0

    for i in range(len(x)):
        dx = x[i] - mean_x
        dy = y[i] - mean_y

        numerator += dx * dy
        sum_x_squared += dx ** 2
        sum_y_squared += dy ** 2

    denominator = (sum_x_squared * sum_y_squared) ** 0.5

    if denominator != 0:
        correlation = numerator / denominator
    else:
        correlation = 0

    pearson_results[feature] = correlation


pearson_table = pd.DataFrame(
    list(pearson_results.items()),
    columns=["Feature", "Pearson Correlation"]
)

print("Pearson Correlation with Survived:")
display(
    pearson_table.sort_values(
        "Pearson Correlation",
        key=lambda x: x.abs(),
        ascending=False
    )
)

# Chi-Square Test from scratch
# Feature: sex
# Target: survived

feature = train_data["sex"].tolist()
target = train_data["survived"].tolist()

categories = sorted(set(feature))
target_values = sorted(set(target))

# Create observed frequency table
observed = {}

for category in categories:
    observed[category] = {}

    for target_value in target_values:
        count = 0

        for i in range(len(feature)):
            if feature[i] == category and target[i] == target_value:
                count += 1

        observed[category][target_value] = count


# Display observed table
observed_table = pd.DataFrame(observed).T

print("Observed Frequency Table:")
display(observed_table)


# Calculate row totals
row_totals = {}

for category in categories:
    row_totals[category] = sum(observed[category].values())


# Calculate column totals
column_totals = {}

for target_value in target_values:
    column_totals[target_value] = sum(
        observed[category][target_value]
        for category in categories
    )


grand_total = sum(column_totals.values())


# Calculate Chi-Square statistic
chi_square = 0

for category in categories:
    for target_value in target_values:

        expected = (
            row_totals[category] *
            column_totals[target_value]
        ) / grand_total

        actual = observed[category][target_value]

        if expected != 0:
            chi_square += ((actual - expected) ** 2) / expected


print("\nChi-Square Statistic:", chi_square)

# ANOVA F-Test from scratch
# Feature: age
# Target: survived

group_0 = []
group_1 = []

for i in range(len(train_data)):
    age_value = train_data.iloc[i]["age"]
    target_value = train_data.iloc[i]["survived"]

    if pd.notna(age_value):
        if target_value == 0:
            group_0.append(age_value)
        else:
            group_1.append(age_value)


# Calculate group means
mean_0 = sum(group_0) / len(group_0)
mean_1 = sum(group_1) / len(group_1)

# Overall mean
all_values = group_0 + group_1
overall_mean = sum(all_values) / len(all_values)

# Between-group sum of squares
SS_between = (
    len(group_0) * (mean_0 - overall_mean) ** 2
    + len(group_1) * (mean_1 - overall_mean) ** 2
)

# Within-group sum of squares
SS_within = 0

for x in group_0:
    SS_within += (x - mean_0) ** 2

for x in group_1:
    SS_within += (x - mean_1) ** 2


# Degrees of freedom
df_between = 2 - 1
df_within = len(all_values) - 2

# Mean squares
MS_between = SS_between / df_between
MS_within = SS_within / df_within

# F-statistic
F_value = MS_between / MS_within

print("Mean Age - Survived = 0:", mean_0)
print("Mean Age - Survived = 1:", mean_1)

print("\nANOVA F-statistic:", F_value)

# Mutual Information from scratch
# Feature: sex
# Target: survived

from math import log2

feature = train_data["sex"].tolist()
target = train_data["survived"].tolist()

# Function to calculate entropy
def entropy(values):
    counts = {}

    for value in values:
        counts[value] = counts.get(value, 0) + 1

    total = len(values)
    result = 0

    for count in counts.values():
        probability = count / total
        result -= probability * log2(probability)

    return result


# Entropy of target
H_Y = entropy(target)

# Calculate conditional entropy H(Y|X)
conditional_entropy = 0

categories = set(feature)

for category in categories:

    target_subset = []

    for i in range(len(feature)):
        if feature[i] == category:
            target_subset.append(target[i])

    probability_x = len(target_subset) / len(feature)

    conditional_entropy += (
        probability_x * entropy(target_subset)
    )


# Mutual Information
mutual_information = H_Y - conditional_entropy

print("Entropy of Target:", H_Y)
print("Conditional Entropy H(Y|X):", conditional_entropy)
print("Mutual Information:", mutual_information)

# Feature Selection Summary

print("FEATURE SELECTION METHODS COMPLETED")
print("=" * 50)

print("\n1. Variance Threshold")
display(variance_table.sort_values("Variance"))

print("\n2. Pearson Correlation")
display(
    pearson_table.sort_values(
        "Pearson Correlation",
        key=lambda x: x.abs(),
        ascending=False
    )
)

print("\n3. Chi-Square Test")
print("Feature: sex")
print("Chi-Square Statistic:", chi_square)

print("\n4. ANOVA F-Test")
print("Feature: age")
print("F-Statistic:", F_value)

print("\n5. Mutual Information")
print("Feature: sex")
print("Mutual Information:", mutual_information)

# Library Verification

from scipy.stats import pearsonr, chi2_contingency, f_oneway
from sklearn.feature_selection import mutual_info_classif

print("LIBRARY VERIFICATION")
print("=" * 50)

# -------- Pearson Verification --------
age_train = train_data["age"].dropna()
survived_age = train_data.loc[age_train.index, "survived"]

library_pearson = pearsonr(age_train, survived_age)[0]

print("\nPearson Correlation")
print("From Scratch:", pearson_results["age"])
print("Library:", library_pearson)


# -------- Chi-Square Verification --------
contingency_table = pd.crosstab(
    train_data["sex"],
    train_data["survived"]
)

library_chi_square = chi2_contingency(
    contingency_table
)[0]

print("\nChi-Square")
print("From Scratch:", chi_square)
print("Library:", library_chi_square)


# -------- ANOVA Verification --------
age_0 = train_data[
    train_data["survived"] == 0
]["age"].dropna()

age_1 = train_data[
    train_data["survived"] == 1
]["age"].dropna()

library_anova = f_oneway(age_0, age_1)[0]

print("\nANOVA F-Test")
print("From Scratch:", F_value)
print("Library:", library_anova)


# -------- Mutual Information Verification --------
sex_encoded = train_data["sex"].map({
    "female": 0,
    "male": 1
}).values

target_values = train_data["survived"].values

library_mi = mutual_info_classif(
    sex_encoded.reshape(-1, 1),
    target_values,
    random_state=42
)[0]

print("\nMutual Information")
print("From Scratch:", mutual_information)
print("Library:", library_mi)

# Before vs After Preprocessing

print("BEFORE vs AFTER PREPROCESSING")
print("=" * 50)

print("\nBEFORE PREPROCESSING")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])
print("Missing Values:", df.isnull().sum().sum())
print("Duplicate Rows:", df.duplicated().sum())

print("\nAFTER PREPROCESSING")
print("Rows:", df_scaled.shape[0])
print("Columns:", df_scaled.shape[1])
print("Missing Values:", df_scaled.isnull().sum().sum())
print("Duplicate Rows:", df_scaled.duplicated().sum())

print("\nTRAIN-TEST DATA")
print("Training Rows:", len(train_data))
print("Testing Rows:", len(test_data))

# Pearson Correlation Visualization

plt.figure(figsize=(10, 5))

plt.bar(
    pearson_table["Feature"],
    pearson_table["Pearson Correlation"]
)

plt.axhline(0, linewidth=1)

plt.title("Pearson Correlation of Features with Survived")
plt.xlabel("Features")
plt.ylabel("Correlation")

plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# FINAL RESULTS SUMMARY

print("=" * 60)
print("MACHINE LEARNING PREPROCESSING - FINAL SUMMARY")
print("=" * 60)

print("\n1. DATASET")
print("Original shape:", df.shape)
print("Final processed shape:", df_scaled.shape)

print("\n2. MISSING VALUES")
print("Missing values before:", df.isnull().sum().sum())
print("Missing values after:", df_clean.isnull().sum().sum())

print("\n3. DUPLICATES")
print("Duplicates before:", df.duplicated().sum())
print("Duplicates after:", df_clean.duplicated().sum())

print("\n4. ENCODING")
print("Label Encoding: sex")
print("One-Hot Encoding: embarked")

print("\n5. OUTLIER DETECTION")
print("IQR outliers in Fare:", len(outliers))
print("Z-score outliers in Fare:", len(z_outliers))
print("Treatment: IQR-based capping")

print("\n6. TRANSFORMATION")
print("Log transformation applied to Fare")

print("\n7. SCALING")
print("Min-Max Normalization applied")
print("Standardization applied")

print("\n8. TRAIN-TEST SPLIT")
print("Training rows:", len(train_data))
print("Testing rows:", len(test_data))

print("\n9. FEATURE SELECTION")
print("Variance Threshold: Completed")
print("Pearson Correlation: Completed")
print("Chi-Square Test: Completed")
print("ANOVA F-Test: Completed")
print("Mutual Information: Completed")

print("\n10. FROM-SCRATCH IMPLEMENTATION")
print("Mean, Median, Mode, Variance, Standard Deviation")
print("IQR, Z-score, Encoding, Scaling")
print("Feature Selection methods")

print("\n" + "=" * 60)
print("PREPROCESSING AND FEATURE SELECTION COMPLETED!")
print("=" * 60)

